INSERT INTO SYSTEM.EPS (CODEPS, NOMBREEPS) VALUES ('EPS001', 'Sura');
INSERT INTO SYSTEM.EPS (CODEPS, NOMBREEPS) VALUES ('EPS002', 'Sanitas');
INSERT INTO SYSTEM.EPS (CODEPS, NOMBREEPS) VALUES ('EPS003', 'Nueva EPS');
INSERT INTO SYSTEM.EPS (CODEPS, NOMBREEPS) VALUES ('EPS004', 'Compensar');
COMMIT;
