-- Insertar datos en la tabla DEPTO con valores válidos para AREAS_CODIGOAREAS
DELETE FROM SYSTEM.DEPTO WHERE CODIGODPTO IN ('D001', 'D002', 'D003', 'D004', 'D005', 'D006'); -- Limpia duplicados

INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, "Adm-Ing", AREAS_CODIGOAREAS) VALUES ('D001', 'Departamento de Transporte', 'Ing', 'A002');
INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, "Adm-Ing", AREAS_CODIGOAREAS) VALUES ('D002', 'Departamento de Mina', 'Ing', 'A002');
INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, "Adm-Ing", AREAS_CODIGOAREAS) VALUES ('D003', 'Depto Maq Amarilla', 'Ing', 'A002');
INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, "Adm-Ing", AREAS_CODIGOAREAS) VALUES ('D004', 'Departamento de SG-SST', 'Ing', 'A002');
INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, "Adm-Ing", AREAS_CODIGOAREAS) VALUES ('D005', 'Departamento Administrativo', 'Adm', 'A001');
INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, "Adm-Ing", AREAS_CODIGOAREAS) VALUES ('D006', 'Departamento Contable', 'Adm', 'A001');
COMMIT;
