-- Insertar datos en la tabla DEPTO
INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, AREAS_CODIGOAREAS, "Adm-Ing", PERSONA_CEDULAPER) 
VALUES ('D001', 'Departamento de Transporte', 'A002', 'Ing', NULL);

INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, AREAS_CODIGOAREAS, "Adm-Ing", PERSONA_CEDULAPER) 
VALUES ('D002', 'Departamento de Mina', 'A002', 'Ing', NULL);

INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, AREAS_CODIGOAREAS, "Adm-Ing", PERSONA_CEDULAPER) 
VALUES ('D003', 'Departamento de Maquina Amarilla', 'A002', 'Ing', NULL);

INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, AREAS_CODIGOAREAS, "Adm-Ing", PERSONA_CEDULAPER) 
VALUES ('D004', 'Departamento de SG-SST', 'A002', 'Ing', NULL);

INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, AREAS_CODIGOAREAS, "Adm-Ing", PERSONA_CEDULAPER) 
VALUES ('D005', 'Departamento Administrativo', 'A001', 'Adm', NULL);

INSERT INTO SYSTEM.DEPTO (CODIGODPTO, NOMBRE, AREAS_CODIGOAREAS, "Adm-Ing", PERSONA_CEDULAPER) 
VALUES ('D006', 'Departamento Contable', 'A001', 'Adm', NULL);

-- Insertar datos en la tabla AREAS
INSERT INTO SYSTEM.AREAS (CODIGOAREAS, NOMBRE, DEPTO_CODIGODPTO) 
VALUES ('A001', 'Area Administrativa', 'D005');

INSERT INTO SYSTEM.AREAS (CODIGOAREAS, NOMBRE, DEPTO_CODIGODPTO) 
VALUES ('A002', 'Area Operativa', 'D001');

COMMIT;
