-- Inserta datos básicos en catálogos para poder usar el formulario

-- Limpia (opcional si es una base nueva)
BEGIN EXECUTE IMMEDIATE 'DELETE FROM SYSTEM.NVR'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DELETE FROM SYSTEM.ESTADOCIVIL'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DELETE FROM SYSTEM.FP'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DELETE FROM SYSTEM.NAC'; EXCEPTION WHEN OTHERS THEN NULL; END; /
BEGIN EXECUTE IMMEDIATE 'DELETE FROM SYSTEM.CT'; EXCEPTION WHEN OTHERS THEN NULL; END; /
COMMIT;

-- NVR
INSERT INTO SYSTEM.NVR (CODIGONR, NIVEL) VALUES ('NR1', 'Bajo');
INSERT INTO SYSTEM.NVR (CODIGONR, NIVEL) VALUES ('NR2', 'Medio');
INSERT INTO SYSTEM.NVR (CODIGONR, NIVEL) VALUES ('NR3', 'Alto');

-- ESTADOCIVIL
INSERT INTO SYSTEM.ESTADOCIVIL (CODIGOEC, NOMBREEC) VALUES ('S', 'Soltero/a');
INSERT INTO SYSTEM.ESTADOCIVIL (CODIGOEC, NOMBREEC) VALUES ('C', 'Casado/a');
INSERT INTO SYSTEM.ESTADOCIVIL (CODIGOEC, NOMBREEC) VALUES ('U', 'Unión libre');

-- FP (Fondos de pensión)
INSERT INTO SYSTEM.FP (CODIGOFP, NOMBREFP) VALUES ('FP01', 'Colpensiones');
INSERT INTO SYSTEM.FP (CODIGOFP, NOMBREFP) VALUES ('FP02', 'Protección');
INSERT INTO SYSTEM.FP (CODIGOFP, NOMBREFP) VALUES ('FP03', 'Porvenir');

-- NAC (Nacionalidades)
INSERT INTO SYSTEM.NAC (CODIGONAC, NOMBRENAC) VALUES ('CO', 'Colombia');
INSERT INTO SYSTEM.NAC (CODIGONAC, NOMBRENAC) VALUES ('VE', 'Venezuela');
INSERT INTO SYSTEM.NAC (CODIGONAC, NOMBRENAC) VALUES ('PE', 'Perú');

-- CT (Centros de trabajo)
INSERT INTO SYSTEM.CT (CODIGOCT, NOMBRECT) VALUES ('CT01', 'Mina 1');
INSERT INTO SYSTEM.CT (CODIGOCT, NOMBRECT) VALUES ('CT02', 'Mina 2');
INSERT INTO SYSTEM.CT (CODIGOCT, NOMBRECT) VALUES ('CT03', 'Planta');

COMMIT;
