
CREATE TABLE SYSTEM.AREAS (
  CODIGOAREAS      VARCHAR2(30 CHAR),
  NOMBRE           VARCHAR2(30 CHAR)
);
-- Crea solamente las tablas requeridas por la app, en el esquema SYSTEM de XEPDB1
-- Ejecutar conectado como SYSTEM@XEPDB1

-- Helpers para eliminar tablas si existen (ignora ORA-00942)
DECLARE
  PROCEDURE drop_if_exists(p_stmt VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_stmt;
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
  END;
BEGIN
  drop_if_exists('DROP TABLE SYSTEM.PERSONA CASCADE CONSTRAINTS');
  drop_if_exists('DROP TABLE SYSTEM.DEPTO CASCADE CONSTRAINTS');
  drop_if_exists('DROP TABLE SYSTEM.CT CASCADE CONSTRAINTS');
  drop_if_exists('DROP TABLE SYSTEM.AREAS CASCADE CONSTRAINTS');
  drop_if_exists('DROP TABLE SYSTEM.CARGO CASCADE CONSTRAINTS');
  drop_if_exists('DROP TABLE SYSTEM.EPS CASCADE CONSTRAINTS');
  drop_if_exists('DROP TABLE SYSTEM.ESTADOCIVIL CASCADE CONSTRAINTS');
  drop_if_exists('DROP TABLE SYSTEM.FP CASCADE CONSTRAINTS');
  drop_if_exists('DROP TABLE SYSTEM.NAC CASCADE CONSTRAINTS');
  drop_if_exists('DROP TABLE SYSTEM.NVR CASCADE CONSTRAINTS');
END;
/

-- Tablas de catálogos
CREATE TABLE SYSTEM.CARGO (
  CODIGOCARGO      VARCHAR2(6 CHAR),
  NOMBRE           VARCHAR2(30 CHAR)
);

CREATE TABLE SYSTEM.CT (
  CODIGOCT         VARCHAR2(6 CHAR),
  NOMBRECT         VARCHAR2(30 CHAR)
);

CREATE TABLE SYSTEM.EPS (
  CODEPS           VARCHAR2(10 BYTE),
  NOMBREEPS        VARCHAR2(30 CHAR)
);

CREATE TABLE SYSTEM.ESTADOCIVIL (
  CODIGOEC         VARCHAR2(30 CHAR),
  NOMBREEC         VARCHAR2(30 CHAR)
);

CREATE TABLE SYSTEM.FP (
  CODIGOFP         VARCHAR2(30 CHAR),
  NOMBREFP         VARCHAR2(30 CHAR)
);

CREATE TABLE SYSTEM.NAC (
  CODIGONAC        VARCHAR2(30 BYTE),
  NOMBRENAC        VARCHAR2(30 CHAR)
);

CREATE TABLE SYSTEM.NVR (
  CODIGONR         VARCHAR2(30 CHAR),
  NIVEL            VARCHAR2(30 CHAR)
);

-- Tabla DEPTO
CREATE TABLE SYSTEM.DEPTO (
  CODIGODPTO       VARCHAR2(30 CHAR),
  NOMBRE           VARCHAR2(30 BYTE),
  "Adm-Ing"        VARCHAR2(30 CHAR),
  AREAS_CODIGOAREAS VARCHAR2(30 CHAR)
);

-- Tabla PERSONA (coincide con lo que usa server.js)
CREATE TABLE SYSTEM.PERSONA (
  CEDULAPER            VARCHAR2(10 CHAR),
  NOMBREPER            VARCHAR2(25 CHAR),
  FECHAPER             DATE,
  EDADPER              VARCHAR2(2 CHAR),
  FECHAINGRESOPER      DATE,
  TELEFONOPER          VARCHAR2(10 CHAR),
  SEXOPER              VARCHAR2(8 CHAR),
  CONTRATO20PER        VARCHAR2(10 CHAR),
  CORREOPER            VARCHAR2(25 CHAR),
  EXAMENINGRESOPER     DATE,
  ESTADOCIVIL_CODIGOEC VARCHAR2(15 CHAR),
  CARGO_CODIGOCARGO    VARCHAR2(6 CHAR),
  CT_CODIGOCT          VARCHAR2(30 CHAR),
  NVR_CODIGONR         VARCHAR2(30 CHAR),
  EPS_CODEPS           VARCHAR2(30 BYTE),
  NAC_CODIGONAC        VARCHAR2(30 BYTE),
  FP_CODIGOFP          VARCHAR2(30 CHAR),
  AREAS_CODIGOAREAS    VARCHAR2(30 CHAR)
);

-- Claves primarias simples (opcionales)
ALTER TABLE SYSTEM.AREAS       ADD CONSTRAINT PK_AREAS PRIMARY KEY (CODIGOAREAS);
ALTER TABLE SYSTEM.CARGO       ADD CONSTRAINT PK_CARGO PRIMARY KEY (CODIGOCARGO);
ALTER TABLE SYSTEM.CT          ADD CONSTRAINT PK_CT PRIMARY KEY (CODIGOCT);
ALTER TABLE SYSTEM.EPS         ADD CONSTRAINT PK_EPS PRIMARY KEY (CODEPS);
ALTER TABLE SYSTEM.ESTADOCIVIL ADD CONSTRAINT PK_ESTADOCIVIL PRIMARY KEY (CODIGOEC);
ALTER TABLE SYSTEM.FP          ADD CONSTRAINT PK_FP PRIMARY KEY (CODIGOFP);
ALTER TABLE SYSTEM.NAC         ADD CONSTRAINT PK_NAC PRIMARY KEY (CODIGONAC);
ALTER TABLE SYSTEM.NVR         ADD CONSTRAINT PK_NVR PRIMARY KEY (CODIGONR);
ALTER TABLE SYSTEM.DEPTO       ADD CONSTRAINT PK_DEPTO PRIMARY KEY (CODIGODPTO);
ALTER TABLE SYSTEM.PERSONA     ADD CONSTRAINT PK_PERSONA PRIMARY KEY (CEDULAPER);

COMMIT;

-- CARGO
CREATE TABLE SYSTEM.CARGO (
  CODIGOCARGO      VARCHAR2(6 CHAR),
  NOMBRE           VARCHAR2(30 CHAR)
);

-- CT (Centros de Trabajo)
CREATE TABLE SYSTEM.CT (
  CODIGOCT         VARCHAR2(6 CHAR),
  NOMBRECT         VARCHAR2(30 CHAR)
);

-- DEPTO
CREATE TABLE SYSTEM.DEPTO (
  CODIGODPTO       VARCHAR2(30 CHAR),
  NOMBRE           VARCHAR2(30 BYTE),
  "Adm-Ing"        VARCHAR2(30 CHAR),
  AREAS_CODIGOAREAS VARCHAR2(30 CHAR)
);

-- EPS
CREATE TABLE SYSTEM.EPS (
  CODEPS           VARCHAR2(10 BYTE),
  NOMBREEPS        VARCHAR2(30 CHAR)
);

-- ESTADOCIVIL
CREATE TABLE SYSTEM.ESTADOCIVIL (
  CODIGOEC         VARCHAR2(30 CHAR),
  NOMBREEC         VARCHAR2(30 CHAR)
);

-- FP (Fondo de Pensión)
CREATE TABLE SYSTEM.FP (
  CODIGOFP         VARCHAR2(30 CHAR),
  NOMBREFP         VARCHAR2(30 CHAR)
);

-- NAC (Nacionalidad)
CREATE TABLE SYSTEM.NAC (
  CODIGONAC        VARCHAR2(30 BYTE),
  NOMBRENAC        VARCHAR2(30 CHAR)
);

-- NVR (Nivel de Riesgo)
CREATE TABLE SYSTEM.NVR (
  CODIGONR         VARCHAR2(30 CHAR),
  NIVEL            VARCHAR2(30 CHAR)
);

-- PERSONA
CREATE TABLE SYSTEM.PERSONA (
  CEDULAPER            VARCHAR2(10 CHAR),
  NOMBREPER            VARCHAR2(25 CHAR),
  FECHAPER             DATE,
  EDADPER              VARCHAR2(2 CHAR),
  FECHAINGRESOPER      DATE,
  TELEFONOPER          VARCHAR2(10 CHAR),
  SEXOPER              VARCHAR2(8 CHAR),
  CONTRATO20PER        VARCHAR2(10 CHAR),
  CORREOPER            VARCHAR2(25 CHAR),
  EXAMENINGRESOPER     DATE,
  ESTADOCIVIL_CODIGOEC VARCHAR2(15 CHAR),
  CARGO_CODIGOCARGO    VARCHAR2(6 CHAR),
  CT_CODIGOCT          VARCHAR2(30 CHAR),
  NVR_CODIGONR         VARCHAR2(30 CHAR),
  EPS_CODEPS           VARCHAR2(30 BYTE),
  NAC_CODIGONAC        VARCHAR2(30 BYTE),
  FP_CODIGOFP          VARCHAR2(30 CHAR),
  AREAS_CODIGOAREAS    VARCHAR2(30 CHAR)
);

-- (Opcional) Puedes añadir claves primarias/foráneas después de validar datos existentes.
